"""Application configuration.

This package exposes configuration constants (e.g., scraper endpoints) in a
single import location.
"""

from .config import (
    ASHBY_API_URL,
    AUTODESK_API_URL,
    CIBC_API_URL,
    DEFAULT_WORKDAY_API_URL,
    DEFAULT_WORKDAY_COMPANY_URL,
    DEFAULT_HEADERS,
    DEFAULT_WORKDAY_PAYLOAD,
    DEFAULT_RIPPLING_PAYLOAD,
    DWAVE_API_URL,
    MOTOROLA_COMPANY_URL,
    MOTOROLA_API_URL,
    MOTOROLA_PAYLOAD,
    NVIDIA_API_URL,
    NVIDIA_COMPANY_URL,
    RBC_API_URL,
    SALESFORCE_API_URL,
    STRIPE_GREENHOUSE_API_URL,
    TD_COMPANY_URL,
    TD_API_URL,
    TELUS_API_URL,
    DELOITTE_API_URL,
    DELOITTE_PAYLOAD,
)

__all__ = [
    "ASHBY_API_URL",
    "AUTODESK_API_URL",
    "CIBC_API_URL",
    "DEFAULT_WORKDAY_API_URL",
    "DEFAULT_WORKDAY_COMPANY_URL",
    "DEFAULT_HEADERS",
    "DEFAULT_RIPPLING_PAYLOAD",
    "DEFAULT_WORKDAY_PAYLOAD",
    "DWAVE_API_URL",
    "MOTOROLA_COMPANY_URL",
    "MOTOROLA_API_URL",
    "MOTOROLA_PAYLOAD",
    "NVIDIA_API_URL",
    "NVIDIA_COMPANY_URL",
    "RBC_API_URL",
    "SALESFORCE_API_URL",
    "STRIPE_GREENHOUSE_API_URL",
    "TD_COMPANY_URL",
    "TD_API_URL",
    "TELUS_API_URL",
    "DELOITTE_API_URL",
    "DELOITTE_PAYLOAD",
]
